### PR TITLE
updown.sh based on netport.yaml

### PR DESCRIPTION
**Pull request by rondv**
updown.sh scripts can now be used by anyone with looped interfaces listed in netport.yaml

### CODE REVIEW

**Review by tgrennan — CHANGES_REQUESTED** [review]
First, all these scripts should be implemented in go but until then, their path must be relative to CWD as since go.mod, I no longer run w/in GOPATH. e.g. my integration trees are in ~/maint and my contribution trees are in ~/devel

**Comment by rondv** [comment]
I thought stig and I the only users of updown, do u also use them?

**Comment by tgrennan** [comment]
I don't know, is updown.sh called from any test case?

**Comment by rondv** [comment]
No.  It's for unit testing only

**Pull request closed without merging**
